version: '3'
services:
  frontend-service:
    build:
      context: .
      dockerfile: ./cmd/frontend-service/Dockerfile
    deploy:
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - service-network
    ports:
      - 8080:8080
#  worker-service:
#    build:
#      context: .
#      dockerfile: ./cmd/worker-service/Dockerfile
#    deploy:
#      replicas: 1
#    depends_on:
#      postgres:
#        condition: service_healthy
#      vault:
#        condition: service_started
#    networks:
#      - service-network
  postgres:
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - service-network
    ports:
      - 5432:5432
    expose:
      - 5432

networks:
  service-network:
    driver: bridge