// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Returns a list of wallets.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "default:10",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default:0",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIReturn"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIReturn"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Increases or decrease the balance of the respective currency in a wallet.",
                "parameters": [
                    {
                        "description": "raw",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EventList"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/models.APIEventReturn"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIReturn"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIEventReturn": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Event"
                },
                "result": {
                    "$ref": "#/definitions/models.EventResult"
                }
            }
        },
        "models.APIReturn": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                },
                "responseTime": {
                    "type": "integer"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "models.Event": {
            "type": "object",
            "properties": {
                "app": {
                    "type": "string"
                },
                "attributes": {
                    "$ref": "#/definitions/models.EventAttributes"
                },
                "meta": {
                    "$ref": "#/definitions/models.EventMeta"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "wallet": {
                    "type": "string"
                }
            }
        },
        "models.EventAttributes": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                }
            }
        },
        "models.EventList": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Event"
                    }
                }
            }
        },
        "models.EventMeta": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "string"
                }
            }
        },
        "models.EventResult": {
            "type": "object",
            "properties": {
                "errorDetails": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "frontend service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
