// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Increases the balance of the respective currency in a wallet.",
                "parameters": [
                    {
                        "description": "raw",
                        "name": "_",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EventList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIReturn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIReturn"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIReturn": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                },
                "responseTime": {
                    "type": "integer"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "models.Attributes": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                }
            }
        },
        "models.Event": {
            "type": "object",
            "properties": {
                "app": {
                    "type": "string"
                },
                "attributes": {
                    "$ref": "#/definitions/models.Attributes"
                },
                "meta": {
                    "$ref": "#/definitions/models.Meta"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "wallet": {
                    "type": "string"
                }
            }
        },
        "models.EventList": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Event"
                    }
                }
            }
        },
        "models.Meta": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "frontend service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
