basePath: /
definitions:
  models.APIEventReturn:
    properties:
      data:
        $ref: '#/definitions/models.Event'
      result:
        $ref: '#/definitions/models.EventResult'
    type: object
  models.APIReturn:
    properties:
      response:
        type: string
      responseTime:
        type: integer
      statusCode:
        type: integer
    type: object
  models.Event:
    properties:
      app:
        type: string
      attributes:
        $ref: '#/definitions/models.EventAttributes'
      meta:
        $ref: '#/definitions/models.EventMeta'
      time:
        type: string
      type:
        type: string
      wallet:
        type: string
    type: object
  models.EventAttributes:
    properties:
      amount:
        type: string
      currency:
        type: string
    type: object
  models.EventList:
    properties:
      events:
        items:
          $ref: '#/definitions/models.Event'
        type: array
    type: object
  models.EventMeta:
    properties:
      user:
        type: string
    type: object
  models.EventResult:
    properties:
      errorDetails:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
  description: frontend service
  version: "1.0"
paths:
  /:
    get:
      parameters:
      - description: default:10
        in: query
        name: limit
        type: integer
      - description: default:0
        in: query
        name: cursor
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIReturn'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIReturn'
      summary: Returns a list of wallets.
    post:
      consumes:
      - application/json
      parameters:
      - description: raw
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/models.EventList'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/models.APIEventReturn'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIReturn'
      summary: Increases or decrease the balance of the respective currency in a wallet.
swagger: "2.0"
